site_name: HoneyDB Agent Docs
theme: readthedocs
markdown_extensions:
  - admonition
pages:
  - Home: index.md
  - Agent Service: agent_service.md
  - Configuration: configuration.md
  - Plugins: plugins.md
  - Services: services.md
